version: '3'
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./university-api/data:/data/db
    ports:
      - '27017:27017'
  mongo-seed:
    container_name: mongo-seed
    build: ./load-fixtures
    links:
      - mongo
    volumes:
      - ./load-fixtures/fixtures:/fixtures
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - '8081:8081'
  api:
    container_name: api
    restart: always
    build:
      context: ./university-api
      args:
        PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - mongo-seed
    links:
      - mongo
      - spa
    environment:
      WAIT_HOSTS: mongo:27017
  spa:
    container_name: spa
    restart: always
    build:
      context: ./university-spa
      args:
        PORT: 80
    ports:
      - "80:80"
    depends_on:
      - mongo
      - mongo-seed
    links:
      - api
    environment:
      WAIT_HOSTS: mongo:27017, api:3001